name: Deploy all branches to GitHub Pages

on:
  push:
    branches:
      - main
      - David-Luto
      - Valdez-Mark
      - buan
      - jacob
      - nino

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload branch content
        uses: actions/upload-pages-artifact@v2
        with:
          path: .
          name: ${{ github.ref_name }}

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./all-branches

      - name: Restructure into subfolders
        run: |
          mkdir site
          for branch in main David-Luto Valdez-Mark buan jacob nino; do
            if [ -d "all-branches/$branch" ]; then
              mkdir -p "site/$branch"
              cp -r "all-branches/$branch"/* "site/$branch"/ || true
            fi
          done

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: ./site
